// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csjjfgklyzvnjdemdcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzampmZ2tseXp2bmpkZW1kY3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzE0MDcsImV4cCI6MjA2NzcwNzQwN30.iWm4I_jm0di-XstiXKbIqlYLX5kVIXfI09r0nq8Ee68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});